In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("./data/SURVEY.csv")

In [4]:
df.head(10)
# 분석 Target = SATISFACTION (만족도)

ORDER_ID  DELIVERY_TIME  BASKET_TIME  COMP_NUM  TIME_ON_WEBSITE  \
0  Z0000000001           24.0         73.8         8             31.3   
1  Z0000000002           24.0          6.1         3             32.2   
2  Z0000000003           34.4         76.3         3             11.9   
3  Z0000000004           29.1          7.1         8             10.1   
4  Z0000000005           24.0          3.5         4             18.0   
5  Z0000000006           24.0         19.8         5             56.8   
6  Z0000000007           25.8         77.6         1             53.8   
7  Z0000000008           27.7          6.1         8              5.2   
8  Z0000000009           24.0          1.3         5              7.4   
9  Z0000000010           24.0          1.7         7             45.9   

   GIFT_OR_NOT  SALE_OR_NOT  SATISFACTION  
0            0            1             5  
1            0            0             5  
2            0            0             5  
3            0            1             5  
4            0            0             5  
5            0            1             3  
6            0            0             3  
7            0            0             5  
8            0            0             5  
9            0            0             5

In [11]:
X = df[['DELIVERY_TIME', 'BASKET_TIME', 'COMP_NUM', 'TIME_ON_WEBSITE', 'GIFT_OR_NOT', 'SALE_OR_NOT']]
y = df['SATISFACTION']

In [12]:
from sklearn.model_selection import train_test_split

X_tn, X_te, y_tn, y_te = train_test_split(X, y, random_state = 0)
# random_state는 일종의 Seed 값으로, 임의의 정수를 사용하면 됨

In [16]:
# 데이터 표준화
from sklearn.preprocessing import StandardScaler

std_scale = StandardScaler()
std_scale.fit(X_tn)
# X 전체를 사용하면 Test Data도 평균과 표준편차를 구하는 데에 사용하는 것이기 때문에 제외
X_tn_std = std_scale.transform(X_tn)
X_te_std = std_scale.transform(X_te)

In [23]:
pd.DataFrame(X_tn_std).head(10)

0         1         2         3         4         5
0  0.643065 -0.576863 -1.208729  1.066071 -0.343529 -0.724861
1  5.616310 -0.189033  1.371167 -0.907170 -0.343529  1.379575
2 -0.422630 -0.477331 -0.348764 -0.620627  2.910959 -0.724861
3  0.427773 -0.624913 -0.778746 -0.373157 -0.343529 -0.724861
4 -0.422630 -0.755333  0.511202  1.320053 -0.343529  1.379575
5 -0.422630  2.508612 -0.778746  0.636256 -0.343529 -0.724861
6 -0.314984  1.575076 -0.778746 -0.711800  2.910959 -0.724861
7 -0.422630 -0.837704  0.941184 -0.080102 -0.343529 -0.724861
8 -0.390336 -0.834272  0.081219 -0.457818 -0.343529 -0.724861
9 -0.422630  0.075240 -0.778746 -0.685750 -0.343529 -0.724861

## 선형 회귀분석

In [24]:
from sklearn.linear_model import LinearRegression 

clf_lr =  LinearRegression()
clf_lr.fit(X_tn_std, y_tn)

LinearRegression()

In [25]:
print(clf_lr.coef_) # 계수
print(clf_lr.intercept_) # 절편

# Delivery Time이 가장 큰 영향을 줌을 알 수 있음

[-4.96015522e-01  1.74008222e-01  1.36257321e-01 -1.86985734e-01
 -8.04685447e-02  1.29928118e-04]
4.561111111111111


In [26]:
# 예측
pred_lr = clf_lr.predict(X_te_std)
print(pred_lr)

[ 3.91562071  4.74220138  4.49285818  4.96338708  4.37551961 -2.47720353
  4.39449628  4.80974568  4.83644633  4.79598066  4.33491768  3.92913951
  3.27002704  5.29628631  5.19479389  3.8183336   4.77170443  4.4277418
  5.00333325  4.82154539  4.53593592  4.99337763  4.8794698   4.57238778
  4.33075227  4.66949512  4.97365161  4.73955374  4.33291493  2.14929731
  4.25961062  4.55229875  4.12392361  5.21206988  4.84167899  4.64044049
  4.76614821  3.82462177  4.76987398  4.83666399  4.84767087  4.61886574
  4.97314489  4.14362279  5.3096554   4.84732272  4.65544872  4.8552083
  4.76530784  4.95327987  4.3395061   4.57684869  4.87620529  4.36836187
  4.61384511  4.48588535  4.90418245  4.36758908  4.53967559  3.95655   ]


In [28]:
# 모형 평가 - R 제곱값
# 모형의 설명력을 나타내는 값
from sklearn.metrics import r2_score
print(r2_score(y_te, pred_lr))

0.20184310997489274


In [29]:
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_te, pred_lr))

0.7048168759416156


## 로지스틱 회귀분석

In [30]:
from sklearn.linear_model import LogisticRegression

clf_logi_l2 = LogisticRegression()
clf_logi_l2.fit(X_tn_std, y_tn)

LogisticRegression()

In [32]:
# 로지스틱 회귀분석 모형 추정 계수
print(clf_logi_l2.coef_)
print(clf_logi_l2.intercept_)

[[ 1.21345986 -0.12435226 -0.22928957 -0.53676118 -0.17280063  0.25406188]
 [ 0.51114456 -0.40605131 -0.32023245  0.23322263 -0.24100443  0.05709334]
 [ 0.00965802  0.35318731 -0.13517388  0.24259343  0.42360291 -0.21502064]
 [-0.69562283 -0.82734054  0.27854622  0.4568836  -0.03858163 -0.0720666 ]
 [-1.03863962  1.0045568   0.40614968 -0.39593848  0.02878378 -0.02406797]]
[-4.38918952 -1.31203617  1.60818671  0.44971389  3.64332509]


In [33]:
pred_logistic = clf_logi_l2.predict(X_te_std)
print(pred_logistic)

[5 5 5 5 5 1 5 5 5 5 5 3 3 5 5 3 5 5 5 5 5 5 5 5 5 5 5 5 5 1 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]


In [34]:
# 확률 값으로 예측
pred_proba = clf_logi_l2.predict_proba(X_te_std)
print(pred_proba)

[[7.73616092e-04 2.51920953e-03 4.10700982e-01 2.93583387e-03
  5.83070358e-01]
 [3.16367438e-04 4.21762193e-03 5.69590079e-02 1.16711649e-02
  9.26835838e-01]
 [8.05953208e-04 9.89066178e-03 1.26654529e-01 2.87691271e-02
  8.33879729e-01]
 [1.19165573e-04 2.05198975e-03 2.83028480e-02 2.66804691e-02
  9.42845528e-01]
 [1.01538475e-03 7.18688685e-03 1.32822937e-01 8.12942998e-03
  8.50845361e-01]
 [9.99210038e-01 7.85916069e-04 4.04522261e-06 2.83036758e-10
  1.57357635e-11]
 [2.22176975e-04 1.91816846e-02 2.10666711e-01 1.91989359e-01
  5.77940069e-01]
 [3.84284944e-04 5.53299686e-03 4.41866384e-02 5.40899194e-02
  8.95806160e-01]
 [1.78383934e-04 3.46886390e-03 3.95511377e-02 4.40334651e-02
  9.12768149e-01]
 [2.14356135e-04 3.88916208e-03 4.84126543e-02 2.56353609e-02
  9.21848467e-01]
 [7.96912021e-04 3.92600327e-02 1.92261000e-01 1.77780438e-01
  5.89901617e-01]
 [8.35121979e-05 6.90404944e-03 6.87407043e-01 4.99052350e-02
  2.55700161e-01]
 [6.69236104e-03 2.34781278e-02 7.436414

In [35]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_te, pred_logistic)

print(accuracy)
# 예측 값이 정수이기 때문에 정확도를 구할 수 있음

0.7833333333333333


In [36]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_te, pred_logistic)
print(conf_matrix)

[[ 1  0  0  0  0]
 [ 1  0  0  0  0]
 [ 0  0  1  0  9]
 [ 0  0  1  0  1]
 [ 0  0  1  0 45]]


## Random Forest

In [37]:
from sklearn.ensemble import RandomForestClassifier
clf_rf = RandomForestClassifier(max_depth = 2, random_state = 1225)
clf_rf.fit(X_tn_std, y_tn)

RandomForestClassifier(max_depth=2, random_state=1225)

In [38]:
# 예측
pred_rf = clf_rf.predict(X_te_std)
print(pred_rf)

[5 5 5 5 5 5 5 5 5 5 3 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]


In [39]:
# 정확도
accuracy = accuracy_score(y_te, pred_rf)
print(accuracy)

0.7833333333333333


In [40]:
# Confusion Matrix 확인
conf_matrix = confusion_matrix(y_te, pred_rf)
print(conf_matrix)

[[ 0  0  0  0  1]
 [ 0  0  0  0  1]
 [ 0  0  1  0  9]
 [ 0  0  0  0  2]
 [ 0  0  0  0 46]]
