In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
med = pd.read_csv("Sample Data/medFactor.csv")
med.head(3)

lung  muscle  liver  skeleton  kidneys  heart  step  stamina  stretch  \
0    20      16     52        10       24     23    19       20       23   
1    24      16     52         7       27     16    16       15       31   
2    19      21     57        18       22     23    16       19       42   

   blow  urine  
0    29     67  
1    33     59  
2    40     61

In [3]:
med.describe()

lung      muscle       liver    skeleton     kidneys       heart  \
count  128.000000  128.000000  128.000000  128.000000  128.000000  128.000000   
mean    19.960938   18.820312   54.695312   12.867188   25.640625   23.179688   
std      4.464034    4.088458    7.428990    2.986508    3.805786    4.159106   
min      4.000000    9.000000   26.000000    3.000000   16.000000   11.000000   
25%     17.000000   16.000000   50.750000   11.000000   23.000000   22.000000   
50%     20.000000   19.000000   55.000000   13.000000   26.000000   23.000000   
75%     23.000000   22.000000   60.250000   15.000000   29.000000   25.000000   
max     29.000000   28.000000   69.000000   19.000000   32.000000   56.000000   

             step     stamina     stretch        blow       urine  
count  128.000000  128.000000  128.000000  128.000000  128.000000  
mean    16.171875   15.867188   38.812500   33.539062   66.906250  
std      2.478599    2.651314    7.798395    4.097055   12.565067  
min      4.000000    7.000000   16.000000   17.000000    9.000000  
25%     15.000000   14.000000   34.000000   32.000000   59.000000  
50%     17.000000   16.000000   40.000000   34.000000   67.000000  
75%     18.000000   18.000000   45.000000   36.000000   76.000000  
max     20.000000   20.000000   51.000000   41.000000   93.000000

In [4]:
# pip install factor_analyzer

     |████████████████████████████████| 41 kB 1.3 MB/s eta 0:00:011
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
     |████████████████████████████████| 202 kB 6.5 MB/s eta 0:00:01
     |████████████████████████████████| 3.2 MB 19.8 MB/s eta 0:00:01
     |████████████████████████████████| 98 kB 23.8 MB/s eta 0:00:01
     |████████████████████████████████| 468 kB 21.4 MB/s eta 0:00:01
  Created wheel for factor-analyzer: filename=factor_analyzer-0.4.1-py2.py3-none-any.whl size=42014 sha256=fc13a2394b6ab3ee681b83593e3c4b9f256f10913e46792451dfb02a5431a82d
  Stored in directory: /Users/Yunhee/Library/Caches/pip/wheels/6d/32/bd/460a71becd83f7d77152f437c2fd451f5c87bc19cfcdbfcd24
Successfully built factor-analyzer
  Attempting uninstall: filelock
    Found existing installation: filelock 3.6.0
    Uninstalling filelock-3.6.0:
      Successfully uninstalled filelock-3.6.0
Note: you may need to restart the kernel t

In [5]:
from factor_analyzer.factor_analyzer import calculate_kmo
kmo_all, kmo_model = calculate_kmo(med)
kmo_model

0.6874111268378432

In [6]:
# 초기 인자분석 시행
from factor_analyzer import FactorAnalyzer
fa = FactorAnalyzer(rotation = None)
fa.fit(med)

FactorAnalyzer(rotation=None, rotation_kwargs={})

In [7]:
# 고윳값 구하기
ev, v = fa.get_eigenvalues()
ev

array([3.37918137, 1.48277065, 1.25063015, 0.98047706, 0.7688022 ,
       0.73305114, 0.64039936, 0.62219335, 0.52837181, 0.35193006,
       0.26219284])

In [8]:
# 인자수를 3으로한 인자분석 - 인자회전 Varimax
fa_varimax = FactorAnalyzer(n_factors = 3, rotation = 'varimax', method = 'principal')
# method = 'minres', 'ml', 'principal'
fa_varimax.fit(med)

FactorAnalyzer(method='principal', rotation='varimax', rotation_kwargs={})

In [10]:
# 인자적재 계수
import numpy as np
np.round(fa_varimax.loadings_, 3)

array([[ 0.659,  0.123,  0.16 ],
       [ 0.111, -0.086,  0.785],
       [ 0.783,  0.127,  0.17 ],
       [ 0.185,  0.285,  0.763],
       [ 0.731,  0.23 , -0.135],
       [ 0.646, -0.107,  0.185],
       [ 0.486,  0.48 ,  0.102],
       [ 0.016,  0.62 ,  0.289],
       [ 0.18 ,  0.652,  0.336],
       [ 0.264,  0.699, -0.04 ],
       [-0.066,  0.649, -0.277]])

In [11]:
# 인자 공통성
np.round(fa_varimax.get_communalities(), 3)

array([0.475, 0.636, 0.658, 0.698, 0.606, 0.463, 0.478, 0.468, 0.57 ,
       0.56 , 0.502])